config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :bedrooms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bedroom.rb
class Bedroom < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :rents, dependent: :destroy
  validates :photo, presence: true
end

app/models/rent.rb
class Rent < ApplicationRecord
  belongs_to :user
  belongs_to :bedroom
  validates :user_id, uniqueness: {scope: :bedroom_id}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bedrooms
  has_many :rents  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?  
  before_action :authenticate_user!
  
  include Pundit
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  
    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bedrooms_controller.rb
class BedroomsController < ApplicationController

  def index
    @bedrooms = Bedroom.all
    authorize @bedroom
  end

  def new
    @bedroom = Bedroom.new
    authorize @bedroom
  end
  
  def create
    @bedroom = Bedroom.new(bedroom_params)
    @user = current_user
    @bedroom.user = @user
    authorize @bedroom
    
    if @bedroom.save
      redirect_to bedroom_path(@bedroom)
    else
      render :new
    end
  end

  def show
    @bedroom = Bedroom.find(params[:id])
    authorize @bedroom
  end

  private

  def bedroom_params
    params.require(:bedroom).permit(:description, :price, :rented, :category, :photo)
  end  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  
  def home
    @bedrooms = Bedroom.where(rented: false)
  end
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
  
  def index
    @rents = policy_scope(Rent)
  end 
  
  def create
    @rent = Rent.new(bedroom: @bedroom, user: current_user)
    authorize @rent
    @rent.bedroom.rented = true
    @rent.save
    @bedroom.rented = true
    @bedroom.save
    redirect_to rents_path, notice: "O bedroom #{@bedroom.id} foi alugado."
  end

  private

  def set_bedroom
    @bedroom = Bedroom.find(params[:bedroom_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bedrooms_helper.rb
module BedroomsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rents_helper.rb
module RentsHelper
end

app/views/bedrooms/index.html.erb
<% @bedrooms.each do |bedroom| %>
    <%= link_to bedroom_path(bedroom), class: 'text-decoration-none' do  %>
    <div class="card-product p-3 m-3">
    
        <p><%=bedroom.description%> <strong>VALOR/DIA: R$<%=bedroom.price%></strong></p>
      </div>
     </div>
   <% end %>
  <% end %>

app/views/bedrooms/new.html.erb
<div class="container px-5 w-50 p-2">
  <h2 class="ml-5 my-5">Publique um quarto</h2>
  <%= render 'shared/new_bedroom_form' %>
</div>

app/views/bedrooms/show.html.erb
<div class="container mt-4 mb-4 p-4">
  <h1 class= "ms-3"><%= @bedroom.description %></h1>
  <h1 class= "ms-3"><%= @bedroom.price %></h1>
  <%= cl_image_tag @bedroom.photo.key, height: 300, width: 400, crop: :fill %>
  <% unless policy(@bedroom).edit? %>
      <div class="form-wrapper" style="width: 250px; margin: 0 auto;">
        <p class="mb-1 ms-1">SELECIONE O PERÍODO:</p>
        <%= simple_form_for :search, method: "get" do |f| %>
          <%= f.input :starts_at, label: false, as: :string, required: false, input_html: {class: "datepicker mt-3", id: "range_start"} %>
        <% end %>
      </div>
      <%end%>
  </div>
  <%if policy(@bedroom).destroy? && @bedroom.rented == false %>
    <%= link_to "DELETAR", bedroom_path(@bedroom), method: :delete, data: {confirm: 'Você edroom certeza?'}, class: "btn btn-warning ms-3" %>
  <% elsif @bedroom.rented == false %>
    <%= link_to "ALUGUE", bedroom_rents_path(@bedroom), method: :post, data: {confirm: "Alugar #{@bedroom.id}?"}, class: "btn btn-success ms-3" %>
  <%end %>
  <%= link_to 'VOLTAR', bedrooms_path(@bedroom), class: "btn btn-secondary ms-3" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExercicioRhitmoTech</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="card-category">
  <div>
    <h1>Bedrooms for Rent</h1>
  </div>
  <div class="">
    <p>Encontre o que você precisa</p>
  </div>
</div>
<div class="container w-75 pt-3 pb-5 mb-5">
  </div>
  <h2 class="mt-5 ms-3">Últimos itens publicados</h2>
  <div class="cards card-bedroom ms-3 mt-3">
    <% @bedrooms.last(9).each do |bedroom| %>
    <%= link_to bedroom_path(bedroom), class: 'text-decoration-none' do  %>
      <div class="card-trip">
        <%= cl_image_tag bedroom.photo.key, height: 300, width: 400, crop: :fill %>
        <div class="card-trip-infos">
          <div>
            <h3>(<%=bedroom.category%>)</h3>
            <br>
            <p><%=bedroom.description%></p>
            <p><%=bedroom.price%></p>
          </div>
          <h4 class="card-trip-pricing">R$<%=bedroom.price%>/por dia</h4>
        </div>
        </div>
    <% end %>
    <%end%>
  </div>


</div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "New Bedroom", new_bedroom_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", method: :delete %>
            </div>
          </li>
        <% else %>         
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_new_bedroom_form.html.erb
<%= simple_form_for @bedroom do |f| %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :category %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit, class: 'btn btn-primary w-100' %>
  <% end %>